/** @type {import("prettier").Config} */
module.exports = {
  tabWidth: 2,
  singleQuote: false,
  semi: false,
  trailingComma: "es5",
  endOfLine: "lf",
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
  // This plugin's options
  importOrder: [
    "(^react$/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)|^(next-(.*)$)",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/config/(.*)$",
    "^@/env(.*)$",
    "",
    "^@/hooks/(.*)$",
    "",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "",
    "^@/lib/(.*)$",
    "^types$",
    "^@/types/(.*)$",
    "^@/assets/(.*)$",
    "^@/app/(.*)$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderTypeScriptVersion: "5.0.0",
  importOrderCaseSensitive: false,
}
